### ISSUE TITLE
trace.json data

### ISSUE THREAD

**Issue by niuzhi** [Disalg-ICS-NJU/zookeeper-tla-spec#1]
Hello, can you add the configuration files and related trace data of the TLA+ model in zk_test_v2 and zk_test_v3, thank you! We are expecting a reply

**Comment by Lingzhi-Ouyang** [comment]
Sorry for getting back to you late. The configuration files and the trace data of test specifications are provided now. If you have any other issues please tell us.

**Comment by Lingzhi-Ouyang** [comment]
Sorry for getting back to you late. The configuration files and the trace data of test specifications are provided now. If you have any other issues please tell us.
